version: '2'
services:
    hub:
        privileged: true
        image: dosel/zalenium
        tty: true
        command: >
          start --chromeContainers 1
            --firefoxContainers 0
            --maxDockerSeleniumContainers 10
            --screenWidth 1930 --screenHeight 1090
            --timeZone "Asia/Jerusalem"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
        volumes:
          - /tmp/videos:/home/seluser/videos
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker

    server.local:
        privileged: true
        image: server
        volumes:
          - /tmp/test_results:/tmp/test_results
        environment:
            - BUILD_WEBDRIVERIO
            # This above means that we pass it from the shell env.

