version: '2'
services:
    hub:
        privileged: true
        image: dosel/zalenium:3.3.1j
        tty: true
        command: >
          start --chromeContainers 1
            --firefoxContainers 0
            --maxDockerSeleniumContainers 2
            --screenWidth 1600 --screenHeight 950
            --timeZone "Asia/Jerusalem"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
        volumes:
          - /tmp/videos:/home/seluser/videos
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker

    server.local:
        privileged: true
        image: server
        volumes:
          - /tmp/test_results:/tmp/test_results
          - ${TRAVIS_BUILD_DIR}/travis-cache:/tmp/travis-cache
        environment:
            - BUILD_WEBDRIVERIO
            # This above means that we pass it from the shell env.

